import type { FormConfig } from "@/shared/presentation/types/form-config.types";
import { searchAssets } from "../../../assets/application/use-cases/asset-search.action";

export const workOrderFormConfig: FormConfig = {
  fields: [],
  sections: [
    {
      title: "Información General",
      description: "Datos básicos de la orden de trabajo",
      fields: [
        {
          name: "wo_number",
          label: "Número OT",
          type: "text",
          required: true,
          maxLength: 50,
          placeholder: "OT-2024-001",
          gridCols: 1,
        },
        {
          name: "title",
          label: "Título",
          type: "text",
          required: true,
          maxLength: 200,
          placeholder: "Descripción breve del trabajo",
          gridCols: 2,
        },
        {
          name: "status",
          label: "Estado",
          type: "select",
          required: true,
          options: [
            { label: "Borrador", value: "draft" },
            { label: "Pendiente Aprobación", value: "pending_approval" },
            { label: "Aprobada", value: "approved" },
            { label: "Programada", value: "scheduled" },
            { label: "En Progreso", value: "in_progress" },
            { label: "En Espera", value: "on_hold" },
            { label: "Completada", value: "completed" },
            { label: "Pendiente Revisión", value: "pending_review" },
            { label: "Cerrada", value: "closed" },
            { label: "Cancelada", value: "cancelled" },
          ],
          defaultValue: "draft",
          gridCols: 1,
        },
        {
          name: "description",
          label: "Descripción",
          type: "textarea",
          gridCols: 4,
        },
      ],
    },
    {
      title: "Clasificación",
      description: "Tipo, prioridad y activo relacionado",
      fields: [
        {
          name: "wo_type",
          label: "Tipo de OT",
          type: "select",
          required: true,
          options: [
            { label: "Preventivo", value: "preventive" },
            { label: "Correctivo", value: "corrective" },
            { label: "Predictivo", value: "predictive" },
            { label: "Mejora", value: "improvement" },
            { label: "Inspección", value: "inspection" },
            { label: "Calibración", value: "calibration" },
            { label: "Emergencia", value: "emergency" },
            { label: "Proyecto", value: "project" },
          ],
          defaultValue: "corrective",
          gridCols: 1,
        },
        {
          name: "priority",
          label: "Prioridad",
          type: "select",
          required: true,
          options: [
            { label: "Emergencia", value: "emergency" },
            { label: "Urgente", value: "urgent" },
            { label: "Alta", value: "high" },
            { label: "Normal", value: "normal" },
            { label: "Baja", value: "low" },
            { label: "Planificada", value: "planned" },
          ],
          defaultValue: "normal",
          gridCols: 1,
        },
        {
          name: "asset_id",
          label: "Activo / Equipo",
          type: "autocomplete",
          required: true,
          autocompleteConfig: {
            searchAction: searchAssets,
            returnMode: "code",
            placeholder: "Buscar activo por código o nombre...",
          },
          gridCols: 2,
        },
      ],
    },
    {
      title: "Solicitante y Falla",
      description: "Información sobre quién solicita y descripción del problema",
      fields: [
        {
          name: "requested_by",
          label: "Solicitado por",
          type: "text",
          required: true,
          maxLength: 200,
          gridCols: 1,
        },
        {
          name: "requested_date",
          label: "Fecha de Solicitud",
          type: "date",
          required: true,
          gridCols: 1,
        },
        {
          name: "failure_description",
          label: "Descripción de la Falla",
          type: "textarea",
          placeholder: "Detalle los síntomas o el problema reportado",
          gridCols: 2,
        },
      ],
    },
    {
      title: "Programación",
      description: "Fechas y horarios programados para la ejecución",
      fields: [
        {
          name: "scheduled_start_date",
          label: "Fecha Inicio Programada",
          type: "date",
          gridCols: 1,
        },
        {
          name: "scheduled_start_time",
          label: "Hora Inicio",
          type: "text",
          maxLength: 10,
          placeholder: "08:00",
          gridCols: 1,
        },
        {
          name: "scheduled_end_date",
          label: "Fecha Fin Programada",
          type: "date",
          gridCols: 1,
        },
        {
          name: "scheduled_end_time",
          label: "Hora Fin",
          type: "text",
          maxLength: 10,
          placeholder: "17:00",
          gridCols: 1,
        },
      ],
    },
    {
      title: "Asignación",
      description: "Técnico responsable de ejecutar el trabajo",
      fields: [
        {
          name: "assigned_to",
          label: "Asignado a (ID Usuario)",
          type: "text",
          maxLength: 100,
          placeholder: "ID del técnico asignado",
          gridCols: 2,
        },
        {
          name: "team_id",
          label: "Equipo de Trabajo",
          type: "text",
          maxLength: 100,
          placeholder: "ID del equipo",
          gridCols: 1,
        },
        {
          name: "supervisor_id",
          label: "Supervisor",
          type: "text",
          maxLength: 100,
          placeholder: "ID del supervisor",
          gridCols: 1,
        },
      ],
    },
    {
      title: "Seguridad",
      description: "Requisitos de seguridad para el trabajo",
      fields: [
        {
          name: "requires_shutdown",
          label: "Requiere parada de equipo",
          type: "checkbox",
          gridCols: 1,
        },
        {
          name: "safety_permit_required",
          label: "Requiere permiso de seguridad",
          type: "checkbox",
          gridCols: 1,
        },
        {
          name: "safety_permit_number",
          label: "Número de Permiso",
          type: "text",
          maxLength: 50,
          gridCols: 1,
        },
        {
          name: "lockout_tagout_required",
          label: "Requiere LOTO (Lockout/Tagout)",
          type: "checkbox",
          gridCols: 1,
        },
      ],
    },
    {
      title: "Estimación de Costos",
      description: "Costos estimados para planificación",
      fields: [
        {
          name: "estimated_labor_cost",
          label: "Costo Mano de Obra",
          type: "number",
          min: 0,
          gridCols: 1,
        },
        {
          name: "estimated_parts_cost",
          label: "Costo Repuestos",
          type: "number",
          min: 0,
          gridCols: 1,
        },
        {
          name: "estimated_external_cost",
          label: "Costo Externo",
          type: "number",
          min: 0,
          gridCols: 1,
        },
        {
          name: "cost_center_id",
          label: "Centro de Costo",
          type: "text",
          maxLength: 50,
          gridCols: 1,
        },
      ],
    },
  ],
};
