import type { FormConfig } from "@/shared/presentation/types/form-config.types";
import { searchWarehouses } from "@/app/dashboard/inventory/warehouses/application/use-cases/warehouse-search.action";

export const assetFormConfig: FormConfig = {
  fields: [],
  sections: [
    {
      title: "Identificación",
      description: "Información básica del activo",
      fields: [
        {
          name: "asset_code",
          label: "Código",
          type: "text",
          required: true,
          maxLength: 50,
          placeholder: "EQ-001",
          gridCols: 1,
        },
        {
          name: "asset_name",
          label: "Nombre del Activo",
          type: "text",
          required: true,
          maxLength: 200,
          placeholder: "Centro de Mecanizado CNC",
          gridCols: 2,
        },
        {
          name: "status",
          label: "Estado",
          type: "select",
          required: true,
          options: [
            { label: "Operativo", value: "operational" },
            { label: "En Mantenimiento", value: "under_maintenance" },
            { label: "Inactivo", value: "idle" },
            { label: "Pendiente Instalación", value: "pending_install" },
            { label: "Dado de Baja", value: "decommissioned" },
            { label: "Retirado", value: "retired" },
          ],
          defaultValue: "operational",
          gridCols: 1,
        },
        {
          name: "description",
          label: "Descripción",
          type: "textarea",
          gridCols: 4,
        },
      ],
    },
    {
      title: "Clasificación",
      description: "Categoría y criticidad del activo",
      fields: [
        {
          name: "criticality",
          label: "Criticidad",
          type: "select",
          required: true,
          options: [
            { label: "Crítico - Detiene producción", value: "critical" },
            { label: "Alto impacto", value: "high" },
            { label: "Impacto moderado", value: "medium" },
            { label: "Bajo impacto", value: "low" },
          ],
          defaultValue: "medium",
          gridCols: 1,
        },
        {
          name: "asset_tag",
          label: "Placa/Etiqueta",
          type: "text",
          maxLength: 100,
          placeholder: "Placa física del equipo",
          gridCols: 1,
        },
        {
          name: "barcode",
          label: "Código de Barras",
          type: "text",
          maxLength: 100,
          gridCols: 1,
        },
        {
          name: "area",
          label: "Área de Planta",
          type: "text",
          maxLength: 100,
          placeholder: "Producción, Empaque, etc.",
          gridCols: 1,
        },
        {
          name: "production_line",
          label: "Línea de Producción",
          type: "text",
          maxLength: 100,
          gridCols: 1,
        },
        {
          name: "warehouse_id",
          label: "Almacén/Ubicación",
          type: "autocomplete",
          autocompleteConfig: {
            searchAction: searchWarehouses,
            returnMode: "code",
            placeholder: "Buscar almacén...",
          },
          gridCols: 1,
        },
      ],
    },
    {
      title: "Datos Técnicos",
      description: "Fabricante, modelo y especificaciones",
      fields: [
        {
          name: "manufacturer",
          label: "Fabricante",
          type: "text",
          maxLength: 200,
          placeholder: "Mazak, Siemens, etc.",
          gridCols: 1,
        },
        {
          name: "model",
          label: "Modelo",
          type: "text",
          maxLength: 200,
          gridCols: 1,
        },
        {
          name: "serial_number",
          label: "Número de Serie",
          type: "text",
          maxLength: 100,
          gridCols: 1,
        },
        {
          name: "year_manufactured",
          label: "Año de Fabricación",
          type: "number",
          min: 1900,
          max: 2100,
          gridCols: 1,
        },
      ],
    },
    {
      title: "Medidor (Mantenimiento por uso)",
      description: "Configuración de medidor para mantenimiento basado en horas, km, ciclos, etc.",
      fields: [
        {
          name: "has_meter",
          label: "¿Tiene Medidor?",
          type: "checkbox",
          gridCols: 1,
        },
        {
          name: "meter_type",
          label: "Tipo de Medidor",
          type: "select",
          options: [
            { label: "Horas de operación", value: "hours" },
            { label: "Kilómetros", value: "km" },
            { label: "Ciclos", value: "cycles" },
            { label: "Unidades producidas", value: "units_produced" },
          ],
          gridCols: 1,
        },
        {
          name: "meter_unit",
          label: "Unidad",
          type: "text",
          maxLength: 20,
          placeholder: "hr, km, ciclos",
          gridCols: 1,
        },
        {
          name: "current_meter_reading",
          label: "Lectura Actual",
          type: "number",
          min: 0,
          gridCols: 1,
        },
      ],
    },
    {
      title: "Fechas y Garantía",
      description: "Fechas importantes del activo",
      fields: [
        {
          name: "purchase_date",
          label: "Fecha de Compra",
          type: "date",
          gridCols: 1,
        },
        {
          name: "installation_date",
          label: "Fecha de Instalación",
          type: "date",
          gridCols: 1,
        },
        {
          name: "warranty_start_date",
          label: "Inicio de Garantía",
          type: "date",
          gridCols: 1,
        },
        {
          name: "warranty_end_date",
          label: "Fin de Garantía",
          type: "date",
          gridCols: 1,
        },
      ],
    },
    {
      title: "Costos",
      description: "Información financiera del activo",
      fields: [
        {
          name: "purchase_cost",
          label: "Costo de Compra",
          type: "number",
          min: 0,
          gridCols: 1,
        },
        {
          name: "replacement_cost",
          label: "Costo de Reemplazo",
          type: "number",
          min: 0,
          gridCols: 1,
        },
      ],
    },
    {
      title: "Documentación",
      description: "Enlaces a imagen y manual del equipo",
      fields: [
        {
          name: "image_url",
          label: "URL de Imagen",
          type: "text",
          maxLength: 500,
          placeholder: "https://...",
          gridCols: 2,
        },
        {
          name: "manual_url",
          label: "URL del Manual",
          type: "text",
          maxLength: 500,
          placeholder: "https://...",
          gridCols: 2,
        },
      ],
    },
  ],
};
