import type { BaseEntity } from "@/shared/domain/base/base-entity.types";
import type { KardexMovementType, KardexStatus } from "@/app/dashboard/inventory/shared/types/inventory.types";

export interface Kardex extends BaseEntity {
  kardex_id: string;
  company_id: string;
  movement_number: string;
  movement_date: string;
  movement_datetime: string;
  movement_type: KardexMovementType;
  product_id: string;
  product_sku: string;
  product_name: string;
  lot_id?: string;
  lot_number?: string;
  serial_number?: string;
  expiration_date?: string;
  warehouse_id: string;
  from_location_id?: string;
  to_location_id?: string;
  quantity: number;
  uom_id: string;
  uom_code: string;
  base_quantity?: number;
  conversion_factor: number;
  unit_cost: number;
  total_cost: number;
  currency: string;
  exchange_rate: number;
  base_unit_cost: number;
  base_total_cost: number;
  running_quantity: number;
  running_total_cost: number;
  running_unit_cost: number;
  source_document_type?: string;
  source_document_id?: string;
  source_document_number?: string;
  source_line_id?: string;
  third_party_id?: string;
  third_party_name?: string;
  reason_code?: string;
  reason_description?: string;
  notes?: string;
  status: KardexStatus;
  journal_entry_id?: string;
  posted_at?: string;
  posted_by?: string;
  is_reversal: boolean;
  reversed_kardex_id?: string;
  reversal_kardex_id?: string;
  created_by: string;
  updated_by?: string;
  confirmed_at?: string;
  confirmed_by?: string;
  cancelled_at?: string;
  cancelled_by?: string;
  cancellation_reason?: string;
}
